// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/todo/todo.proto

package chinajuanbob_todo_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TodoStatus int32

const (
	TodoStatus_NEW        TodoStatus = 0
	TodoStatus_INPROGRESS TodoStatus = 1
	TodoStatus_DONE       TodoStatus = 2
)

var TodoStatus_name = map[int32]string{
	0: "NEW",
	1: "INPROGRESS",
	2: "DONE",
}

var TodoStatus_value = map[string]int32{
	"NEW":        0,
	"INPROGRESS": 1,
	"DONE":       2,
}

func (x TodoStatus) String() string {
	return proto.EnumName(TodoStatus_name, int32(x))
}

func (TodoStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_001fa5fe343946f4, []int{0}
}

type Todo struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string               `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Status               TodoStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=chinajuanbob.todo.v1.TodoStatus" json:"status,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_001fa5fe343946f4, []int{0}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Todo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Todo) GetStatus() TodoStatus {
	if m != nil {
		return m.Status
	}
	return TodoStatus_NEW
}

func (m *Todo) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type AddTodoRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTodoRequest) Reset()         { *m = AddTodoRequest{} }
func (m *AddTodoRequest) String() string { return proto.CompactTextString(m) }
func (*AddTodoRequest) ProtoMessage()    {}
func (*AddTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_001fa5fe343946f4, []int{1}
}

func (m *AddTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTodoRequest.Unmarshal(m, b)
}
func (m *AddTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTodoRequest.Marshal(b, m, deterministic)
}
func (m *AddTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTodoRequest.Merge(m, src)
}
func (m *AddTodoRequest) XXX_Size() int {
	return xxx_messageInfo_AddTodoRequest.Size(m)
}
func (m *AddTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTodoRequest proto.InternalMessageInfo

func (m *AddTodoRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type AddTodoResponse struct {
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTodoResponse) Reset()         { *m = AddTodoResponse{} }
func (m *AddTodoResponse) String() string { return proto.CompactTextString(m) }
func (*AddTodoResponse) ProtoMessage()    {}
func (*AddTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_001fa5fe343946f4, []int{2}
}

func (m *AddTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTodoResponse.Unmarshal(m, b)
}
func (m *AddTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTodoResponse.Marshal(b, m, deterministic)
}
func (m *AddTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTodoResponse.Merge(m, src)
}
func (m *AddTodoResponse) XXX_Size() int {
	return xxx_messageInfo_AddTodoResponse.Size(m)
}
func (m *AddTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTodoResponse proto.InternalMessageInfo

func (m *AddTodoResponse) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type UpdateTodoRequest struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string     `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Status               TodoStatus `protobuf:"varint,3,opt,name=status,proto3,enum=chinajuanbob.todo.v1.TodoStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateTodoRequest) Reset()         { *m = UpdateTodoRequest{} }
func (m *UpdateTodoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTodoRequest) ProtoMessage()    {}
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_001fa5fe343946f4, []int{3}
}

func (m *UpdateTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTodoRequest.Unmarshal(m, b)
}
func (m *UpdateTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTodoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTodoRequest.Merge(m, src)
}
func (m *UpdateTodoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTodoRequest.Size(m)
}
func (m *UpdateTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTodoRequest proto.InternalMessageInfo

func (m *UpdateTodoRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateTodoRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *UpdateTodoRequest) GetStatus() TodoStatus {
	if m != nil {
		return m.Status
	}
	return TodoStatus_NEW
}

type UpdateTodoResponse struct {
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTodoResponse) Reset()         { *m = UpdateTodoResponse{} }
func (m *UpdateTodoResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTodoResponse) ProtoMessage()    {}
func (*UpdateTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_001fa5fe343946f4, []int{4}
}

func (m *UpdateTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTodoResponse.Unmarshal(m, b)
}
func (m *UpdateTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTodoResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTodoResponse.Merge(m, src)
}
func (m *UpdateTodoResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTodoResponse.Size(m)
}
func (m *UpdateTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTodoResponse proto.InternalMessageInfo

func (m *UpdateTodoResponse) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type ListTodoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTodoRequest) Reset()         { *m = ListTodoRequest{} }
func (m *ListTodoRequest) String() string { return proto.CompactTextString(m) }
func (*ListTodoRequest) ProtoMessage()    {}
func (*ListTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_001fa5fe343946f4, []int{5}
}

func (m *ListTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTodoRequest.Unmarshal(m, b)
}
func (m *ListTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTodoRequest.Marshal(b, m, deterministic)
}
func (m *ListTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTodoRequest.Merge(m, src)
}
func (m *ListTodoRequest) XXX_Size() int {
	return xxx_messageInfo_ListTodoRequest.Size(m)
}
func (m *ListTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTodoRequest proto.InternalMessageInfo

type ListTodoResponse struct {
	Todos                []*Todo  `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTodoResponse) Reset()         { *m = ListTodoResponse{} }
func (m *ListTodoResponse) String() string { return proto.CompactTextString(m) }
func (*ListTodoResponse) ProtoMessage()    {}
func (*ListTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_001fa5fe343946f4, []int{6}
}

func (m *ListTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTodoResponse.Unmarshal(m, b)
}
func (m *ListTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTodoResponse.Marshal(b, m, deterministic)
}
func (m *ListTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTodoResponse.Merge(m, src)
}
func (m *ListTodoResponse) XXX_Size() int {
	return xxx_messageInfo_ListTodoResponse.Size(m)
}
func (m *ListTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTodoResponse proto.InternalMessageInfo

func (m *ListTodoResponse) GetTodos() []*Todo {
	if m != nil {
		return m.Todos
	}
	return nil
}

type DeleteTodoRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTodoRequest) Reset()         { *m = DeleteTodoRequest{} }
func (m *DeleteTodoRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTodoRequest) ProtoMessage()    {}
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_001fa5fe343946f4, []int{7}
}

func (m *DeleteTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTodoRequest.Unmarshal(m, b)
}
func (m *DeleteTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTodoRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTodoRequest.Merge(m, src)
}
func (m *DeleteTodoRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTodoRequest.Size(m)
}
func (m *DeleteTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTodoRequest proto.InternalMessageInfo

func (m *DeleteTodoRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteTodoResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTodoResponse) Reset()         { *m = DeleteTodoResponse{} }
func (m *DeleteTodoResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTodoResponse) ProtoMessage()    {}
func (*DeleteTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_001fa5fe343946f4, []int{8}
}

func (m *DeleteTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTodoResponse.Unmarshal(m, b)
}
func (m *DeleteTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTodoResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTodoResponse.Merge(m, src)
}
func (m *DeleteTodoResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTodoResponse.Size(m)
}
func (m *DeleteTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTodoResponse proto.InternalMessageInfo

func (m *DeleteTodoResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterEnum("chinajuanbob.todo.v1.TodoStatus", TodoStatus_name, TodoStatus_value)
	proto.RegisterType((*Todo)(nil), "chinajuanbob.todo.v1.Todo")
	proto.RegisterType((*AddTodoRequest)(nil), "chinajuanbob.todo.v1.AddTodoRequest")
	proto.RegisterType((*AddTodoResponse)(nil), "chinajuanbob.todo.v1.AddTodoResponse")
	proto.RegisterType((*UpdateTodoRequest)(nil), "chinajuanbob.todo.v1.UpdateTodoRequest")
	proto.RegisterType((*UpdateTodoResponse)(nil), "chinajuanbob.todo.v1.UpdateTodoResponse")
	proto.RegisterType((*ListTodoRequest)(nil), "chinajuanbob.todo.v1.ListTodoRequest")
	proto.RegisterType((*ListTodoResponse)(nil), "chinajuanbob.todo.v1.ListTodoResponse")
	proto.RegisterType((*DeleteTodoRequest)(nil), "chinajuanbob.todo.v1.DeleteTodoRequest")
	proto.RegisterType((*DeleteTodoResponse)(nil), "chinajuanbob.todo.v1.DeleteTodoResponse")
}

func init() { proto.RegisterFile("proto/todo/todo.proto", fileDescriptor_001fa5fe343946f4) }

var fileDescriptor_001fa5fe343946f4 = []byte{
	// 851 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x95, 0x4f, 0x6f, 0xe3, 0x44,
	0x18, 0xc6, 0x6b, 0x27, 0x4d, 0xd3, 0xb7, 0xbb, 0x49, 0x3a, 0xfc, 0x51, 0x64, 0x01, 0x1d, 0xcc,
	0xbf, 0x28, 0x10, 0xbb, 0xcd, 0x56, 0x02, 0x15, 0x21, 0xe1, 0x55, 0xaa, 0x55, 0xb5, 0xa8, 0xa9,
	0xdc, 0x22, 0x56, 0x5c, 0xd0, 0xc4, 0x33, 0x9b, 0x4c, 0x95, 0xcc, 0x18, 0xcf, 0xb8, 0x65, 0x85,
	0xb8, 0xf0, 0x11, 0xca, 0x0d, 0x71, 0xe2, 0x86, 0xc4, 0x15, 0x89, 0xef, 0xc1, 0x57, 0xe0, 0x23,
	0x70, 0xe0, 0x88, 0x3c, 0x76, 0x36, 0x49, 0xdd, 0x6e, 0x25, 0x0e, 0x7b, 0x69, 0x35, 0xf3, 0xfe,
	0xe6, 0x9d, 0xe7, 0x7d, 0xf2, 0x4c, 0x02, 0xaf, 0xc5, 0x89, 0xd4, 0xd2, 0xd7, 0x92, 0xe6, 0x7f,
	0x3c, 0xb3, 0x46, 0xaf, 0x46, 0x13, 0x2e, 0xc8, 0x79, 0x4a, 0xc4, 0x48, 0x8e, 0x3c, 0x53, 0xb8,
	0xd8, 0x73, 0x76, 0xc6, 0x52, 0x8e, 0xa7, 0xcc, 0x37, 0xcc, 0x28, 0x7d, 0xea, 0x6b, 0x3e, 0x63,
	0x4a, 0x93, 0x59, 0x9c, 0x1f, 0x73, 0xde, 0x28, 0x00, 0x12, 0x73, 0x9f, 0x08, 0x21, 0x35, 0xd1,
	0x5c, 0x0a, 0x55, 0x54, 0x3f, 0x32, 0xff, 0xa2, 0xde, 0x98, 0x89, 0x9e, 0xba, 0x24, 0xe3, 0x31,
	0x4b, 0x7c, 0x19, 0x1b, 0xa2, 0x4c, 0xbb, 0xbf, 0x59, 0x50, 0x3d, 0x93, 0x54, 0xa2, 0x06, 0xd8,
	0x9c, 0xb6, 0x2d, 0x6c, 0x75, 0xd6, 0x43, 0x9b, 0x53, 0xd4, 0x86, 0x8d, 0x48, 0x0a, 0xcd, 0x84,
	0x6e, 0xdb, 0xd8, 0xea, 0x6c, 0x86, 0xf3, 0x25, 0xfa, 0x04, 0x6a, 0x4a, 0x13, 0x9d, 0xaa, 0x76,
	0x05, 0x5b, 0x9d, 0x46, 0x1f, 0x7b, 0x37, 0x8d, 0xe1, 0x65, 0x5d, 0x4f, 0x0d, 0x17, 0x16, 0x3c,
	0xfa, 0x0c, 0xee, 0x4d, 0x89, 0xd2, 0xdf, 0xa4, 0x31, 0x25, 0x9a, 0xd1, 0x76, 0x15, 0x5b, 0x9d,
	0xad, 0xbe, 0xe3, 0xe5, 0xf3, 0x78, 0xf3, 0x81, 0xbd, 0xb3, 0xf9, 0xc0, 0xe1, 0x56, 0xc6, 0x7f,
	0x99, 0xe3, 0x6e, 0x17, 0x1a, 0x01, 0xa5, 0x59, 0xdf, 0x90, 0x7d, 0x9b, 0x32, 0xa5, 0x97, 0x45,
	0x5a, 0x2b, 0x22, 0xdd, 0x00, 0x9a, 0xcf, 0x59, 0x15, 0x4b, 0xa1, 0x18, 0xf2, 0xa0, 0x9a, 0x69,
	0x33, 0x64, 0x76, 0xeb, 0xad, 0xaa, 0x43, 0xc3, 0xb9, 0x97, 0xb0, 0x9d, 0xdf, 0xbc, 0x7c, 0xe3,
	0x4b, 0xb0, 0xc9, 0x1d, 0x00, 0x5a, 0xbe, 0xf8, 0x7f, 0xca, 0xdf, 0x86, 0xe6, 0x17, 0x5c, 0xe9,
	0x25, 0xf1, 0xee, 0x00, 0x5a, 0x8b, 0xad, 0xa2, 0xed, 0x2e, 0xac, 0x67, 0xb8, 0x6a, 0x5b, 0xb8,
	0x72, 0x47, 0xdf, 0x1c, 0x74, 0xdf, 0x81, 0xed, 0x01, 0x9b, 0xb2, 0x17, 0xfa, 0xe2, 0x7a, 0x80,
	0x96, 0xa1, 0xe2, 0xb2, 0x36, 0x6c, 0xa8, 0x34, 0x8a, 0x98, 0x52, 0x06, 0xad, 0x87, 0xf3, 0x65,
	0xd7, 0x07, 0x58, 0x38, 0x81, 0x36, 0xa0, 0x72, 0x7c, 0xf8, 0x55, 0x6b, 0x0d, 0x35, 0x00, 0x8e,
	0x8e, 0x4f, 0xc2, 0xe1, 0xa3, 0xf0, 0xf0, 0xf4, 0xb4, 0x65, 0xa1, 0x3a, 0x54, 0x07, 0xc3, 0xe3,
	0xc3, 0x96, 0xdd, 0xff, 0x73, 0x1d, 0xb6, 0xcc, 0x09, 0x96, 0x5c, 0xf0, 0x88, 0xa1, 0x5f, 0x2d,
	0xa8, 0x04, 0x94, 0xa2, 0x77, 0x6f, 0x1e, 0x60, 0x35, 0x38, 0xce, 0x7b, 0x77, 0x50, 0xb9, 0x5e,
	0xf7, 0xf8, 0x2a, 0xe8, 0xa3, 0x2c, 0x48, 0x98, 0xe0, 0xb3, 0xe1, 0x60, 0x88, 0xb9, 0x66, 0x33,
	0x67, 0x67, 0xc0, 0x54, 0x94, 0x70, 0xf3, 0xa6, 0xf0, 0x53, 0x99, 0x60, 0x42, 0x29, 0x17, 0x63,
	0x4c, 0x84, 0xa9, 0x7b, 0x3f, 0xfe, 0xf5, 0xf7, 0x4f, 0xf6, 0x2b, 0x6e, 0xdd, 0xbf, 0xd8, 0x33,
	0xaf, 0xfd, 0xe0, 0x79, 0x26, 0xfe, 0xb0, 0xa0, 0x96, 0x7f, 0xb4, 0xe8, 0x83, 0x9b, 0x15, 0x94,
	0x12, 0xe7, 0x74, 0xee, 0x06, 0x0b, 0xb5, 0x4f, 0xae, 0x82, 0x8f, 0x51, 0x11, 0x9d, 0x15, 0xc1,
	0x6f, 0x5f, 0x17, 0x6c, 0x1e, 0x60, 0x49, 0x72, 0xbb, 0x7f, 0x7f, 0x2e, 0xd9, 0xff, 0x9e, 0xd3,
	0x1f, 0x16, 0xba, 0x7f, 0xb1, 0xa0, 0x9a, 0x25, 0x07, 0xdd, 0xe2, 0xdb, 0xb5, 0xa0, 0x39, 0xef,
	0xdf, 0x85, 0x15, 0x8a, 0x0f, 0xaf, 0x82, 0x3d, 0x64, 0x62, 0xba, 0x50, 0xab, 0x9c, 0xb7, 0xae,
	0xcb, 0x9d, 0x72, 0x65, 0xd4, 0x9a, 0x72, 0xae, 0x75, 0x0b, 0x6d, 0xce, 0xb5, 0x2a, 0xf4, 0xbb,
	0x05, 0xb5, 0x3c, 0x6d, 0xb7, 0xd9, 0x5a, 0x0a, 0xec, 0x6d, 0xb6, 0x96, 0x43, 0xeb, 0x0e, 0x8d,
	0xad, 0x79, 0xe1, 0xc5, 0xb6, 0xd2, 0x8c, 0x29, 0xd9, 0xda, 0xec, 0xae, 0xda, 0xfa, 0xf0, 0x5f,
	0xfb, 0x2a, 0xf8, 0xc7, 0x46, 0x13, 0xb8, 0x67, 0x7a, 0xa9, 0x3c, 0xc1, 0xee, 0x69, 0xb1, 0x8e,
	0x13, 0x79, 0xce, 0x22, 0x8d, 0x3e, 0x9c, 0x68, 0x1d, 0xab, 0x03, 0xdf, 0x1f, 0x73, 0x3d, 0x49,
	0x47, 0x5e, 0x24, 0x67, 0xfe, 0xb2, 0x66, 0xd3, 0xb1, 0x17, 0xc9, 0xd9, 0x4c, 0x0a, 0xe7, 0xf5,
	0xe5, 0xca, 0xe7, 0xe3, 0x19, 0xe1, 0xd3, 0xec, 0x40, 0xbf, 0xb2, 0xe7, 0xed, 0x76, 0x6d, 0xcb,
	0xee, 0xb7, 0x48, 0x1c, 0x4f, 0x79, 0x64, 0xbe, 0xfc, 0xfd, 0x73, 0x25, 0xc5, 0x41, 0x69, 0x27,
	0x3c, 0x81, 0xca, 0xfe, 0xee, 0x03, 0x74, 0x04, 0x8f, 0x42, 0xa6, 0xd3, 0x44, 0x30, 0x8a, 0x2f,
	0x27, 0x4c, 0x60, 0x3d, 0x61, 0x38, 0x55, 0x2c, 0xc1, 0x54, 0x32, 0x85, 0x85, 0xd4, 0x78, 0x42,
	0x2e, 0x18, 0x8e, 0x59, 0x32, 0xe3, 0x4a, 0x65, 0xd3, 0x6b, 0x89, 0x89, 0x79, 0xc8, 0x86, 0x4d,
	0x98, 0x92, 0x69, 0x12, 0x31, 0x2f, 0xfc, 0x34, 0xeb, 0xb8, 0x8f, 0xf6, 0xa1, 0x5b, 0xee, 0x38,
	0xa7, 0x16, 0x5d, 0xd9, 0x77, 0x5c, 0x69, 0x0f, 0xd5, 0xa0, 0xfa, 0xb3, 0x6d, 0x6d, 0x7c, 0xbd,
	0x0b, 0x4d, 0xd8, 0x7c, 0x48, 0x14, 0x8f, 0x82, 0x54, 0x4f, 0x90, 0x5d, 0xb7, 0xe0, 0x4d, 0x80,
	0x20, 0xe6, 0x8f, 0xd9, 0x33, 0xb3, 0xd3, 0xac, 0xdb, 0xce, 0xe6, 0x93, 0x5e, 0x70, 0x72, 0xd4,
	0x7b, 0xcc, 0x9e, 0x61, 0x7b, 0xb4, 0x03, 0xf7, 0x97, 0x4f, 0xac, 0x41, 0x63, 0x85, 0x5f, 0x1b,
	0xd5, 0xcc, 0x6f, 0xcc, 0x83, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xb5, 0x93, 0xf3, 0x91,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoServiceClient is the client API for TodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoServiceClient interface {
	Add(ctx context.Context, in *AddTodoRequest, opts ...grpc.CallOption) (*AddTodoResponse, error)
	Update(ctx context.Context, in *UpdateTodoRequest, opts ...grpc.CallOption) (*UpdateTodoResponse, error)
	List(ctx context.Context, in *ListTodoRequest, opts ...grpc.CallOption) (*ListTodoResponse, error)
	Delete(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*DeleteTodoResponse, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) Add(ctx context.Context, in *AddTodoRequest, opts ...grpc.CallOption) (*AddTodoResponse, error) {
	out := new(AddTodoResponse)
	err := c.cc.Invoke(ctx, "/chinajuanbob.todo.v1.TodoService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) Update(ctx context.Context, in *UpdateTodoRequest, opts ...grpc.CallOption) (*UpdateTodoResponse, error) {
	out := new(UpdateTodoResponse)
	err := c.cc.Invoke(ctx, "/chinajuanbob.todo.v1.TodoService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) List(ctx context.Context, in *ListTodoRequest, opts ...grpc.CallOption) (*ListTodoResponse, error) {
	out := new(ListTodoResponse)
	err := c.cc.Invoke(ctx, "/chinajuanbob.todo.v1.TodoService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) Delete(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*DeleteTodoResponse, error) {
	out := new(DeleteTodoResponse)
	err := c.cc.Invoke(ctx, "/chinajuanbob.todo.v1.TodoService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServiceServer is the server API for TodoService service.
type TodoServiceServer interface {
	Add(context.Context, *AddTodoRequest) (*AddTodoResponse, error)
	Update(context.Context, *UpdateTodoRequest) (*UpdateTodoResponse, error)
	List(context.Context, *ListTodoRequest) (*ListTodoResponse, error)
	Delete(context.Context, *DeleteTodoRequest) (*DeleteTodoResponse, error)
}

// UnimplementedTodoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTodoServiceServer struct {
}

func (*UnimplementedTodoServiceServer) Add(ctx context.Context, req *AddTodoRequest) (*AddTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedTodoServiceServer) Update(ctx context.Context, req *UpdateTodoRequest) (*UpdateTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedTodoServiceServer) List(ctx context.Context, req *ListTodoRequest) (*ListTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedTodoServiceServer) Delete(ctx context.Context, req *DeleteTodoRequest) (*DeleteTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chinajuanbob.todo.v1.TodoService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).Add(ctx, req.(*AddTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chinajuanbob.todo.v1.TodoService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).Update(ctx, req.(*UpdateTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chinajuanbob.todo.v1.TodoService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).List(ctx, req.(*ListTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chinajuanbob.todo.v1.TodoService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).Delete(ctx, req.(*DeleteTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chinajuanbob.todo.v1.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _TodoService_Add_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TodoService_Update_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TodoService_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TodoService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/todo/todo.proto",
}
